image: node:11

cache:
  paths:
  - node_modules/

before_script:
  - apt-get update
  - apt-get install --force-yes -y default-jre
  - npm install
  - npm install -g bower
  - bower install --allow-root

pages:
  script:
  - npm run build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - tags

lint:
  script:
  - npm run build
