image: node:7.5.0

cache:
  paths:
  - node_modules/

pages:
  script:
  - npm install
  - npm install -g bower
  - bower install --allow-root
  - npm run build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master
