image: node:14

cache:
  paths:
  - node_modules/

before_script:
  - apt-get update
  - apt-get install --force-yes -y default-jre
  - npm ci

pages:
  script:
  - npm run build
  - mv _site public
  artifacts:
    paths:
    - public
  only:
  - tags
  after_script:
  - npm run deploy

lint:
  script:
  - npm run build
  - npm test
  except:
  - tags
