name: Check Links

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 25.x
        uses: actions/setup-node@v6
        with:
          node-version: 25.x
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      # - name: Check links for changed files
      #   id: check-links-changed-files
      #   uses: lycheeverse/lychee-action@v2
      #   env:
      #     ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
